#! /bin/bash
#
#   apiall - Upload all 0MQ manuals to api.zero.mq
#   Part of the ztools/apisite toolkit.
#
#   Author: Pieter Hintjens <ph@imatix.com>
#   License: public domain
#
#   syntax: apiall
#
#   Requires these gits be checked out parallel to the ztools git:
#
#   zeromq2-x - 2.2 release
#   zeromq3-x - 3.2 release
#   libzmq    - 3.3 release
#
TOOLDIR=`dirname $0`

#               Directory        Tag      Category
$TOOLDIR/apione ../../zeromq2-x  v2.2.0   2-2
$TOOLDIR/apione ../../zeromq3-x  v3.2.2   3-2
$TOOLDIR/apione ../../libzmq     v3.3.0   3-3
