#! /bin/bash
#
#   apiall - Upload all 0MQ manuals to api.zero.mq
#   Part of the ztools/apisite toolkit.
#
#   Author: Pieter Hintjens <ph@imatix.com>
#   License: public domain
#
#   syntax: apiall
#
#   Requires these gits be checked out parallel to the ztools git:
#
#   libzmq - current 3.0 master
#   zeromq2-1 - 2.1 release
#   zeromq2-0 - 2.0 release
#
TOOLDIR=`dirname $0`

#               Directory        Branch   Category
$TOOLDIR/apione ../../libzmq     master   3-0
$TOOLDIR/apione ../../zeromq2-1  v2.1.5   2-1
$TOOLDIR/apione ../../zeromq2-0  v2.0.11  2-0
