#! /bin/bash
#
#   apiall - Upload all 0MQ manuals to api.zero.mq
#   Part of the ztools/apisite toolkit.
#
#   Author: Pieter Hintjens <ph@imatix.com>
#   License: public domain
#
#   syntax: apiall
#
#   Requires these gits be checked out parallel to the ztools git:
#
#   zeromq2 - current master and older versions
#   zeromq2-1 - 2.1 release
#
if test "x$ZEROMQ2_MASTER" = "x"; then
    ZEROMQ2_MASTER="../../zeromq2"
fi

if test "x$ZEROMQ2_RELEASE" = "x"; then
    ZEROMQ2_RELEASE="../../zeromq2-1"
fi

./apione "$ZEROMQ2_MASTER" master  master
./apione "$ZEROMQ2_MASTER" v2.1.0  2-1-0
./apione "$ZEROMQ2_MASTER" v2.0.10 2-0-10
./apione "$ZEROMQ2_MASTER" v2.0.9  2-0-9
./apione "$ZEROMQ2_MASTER" v2.0.8  2-0-8
./apione "$ZEROMQ2_MASTER" v2.0.7  2-0-7
./apione "$ZEROMQ2_MASTER" v2.0.6  2-0-6

#   2.1 is in its own release git
./apione "$ZEROMQ2_RELEASE" v2.1.1  2-1-1
