#! /bin/bash
#
#   apisite - Upload all 0MQ manuals to api.zero.mq
#   Part of the ztools/apisite toolkit.
#
#   Author: Pieter Hintjens <ph@imatix.com>
#   License: public domain
#
#   syntax: apisite [ [ zmq_dir ] branch category ]
#
#   Without arguments, assumes 0MQ is in ../../zeromq2, and processes the
#   versions released from that git (2.1.0 back to 2.0.6).
#
#   With arguments, processes a single branch/tag from a specified git
#   repository location. E.g. "apisite ../../zeromq2-2-1 master 2-1-1".
#
#   See README.md for installation & configuration.

#   ZMQ_DIR comes from the command line, the environment, or a default
#
if [ ! -z "$1" ]; then
    ZMQ_DIR=$1
elif [ -z "$ZMQ_DIR" ]; then
    ZMQ_DIR=../../zeromq2       #   Default location is sibling of ztools
fi
if [ ! -f $ZMQ_DIR/doc/zmq.txt ]; then
    echo "Can't find 0MQ doc directory in $ZMQ_DIR"
    exit
fi

OWN_DIR=$PWD

#   This option controls whether we actually upload or not
#   Set to 0 to suppress Wikidot uploads for testing
#
UPLOAD=1

#   This function builds and uploads one branch's documentation
#   $1 = branch name or tag name
#   $2 = category name for resulting pages
#
function do_branch {
    echo "Building docs for $1..."
    cd $ZMQ_DIR
    git checkout $1
    sh ./autogen.sh > /dev/null 2>&1
    ./configure -q
    cd doc
    rm *.xml
    for a in *.txt; do make `basename $a .txt`.xml; done

    cd $OWN_DIR
    export CATEGORY=$2

    echo "Generating XML pages for manual..."
    cd $ZMQ_DIR/doc
    for FILE in zmq zmq_*.txt; do
        BASE=`basename $FILE .txt`
        make -q $BASE.xml;
        FILES="$FILES $BASE"
    done

    cd $OWN_DIR
    echo "Generating Wikidot pages..."
    for FILE in $FILES; do
        perl ./xml2wd.pl $ZMQ_DIR/doc/$FILE.xml > $FILE.wd
    done

    if [ $UPLOAD -eq 1 ]; then
        echo "Uploading to api.zero.mq/$CATEGORY..."

        #   Send table of contents as category:_start
        python ./sendpage.py $CATEGORY "_start" "ØMQ API"

        #   Now send individual man pages
        for FILE in $FILES; do
            if [ -f $ZMQ_DIR/doc/$FILE.1 ]; then
                TITLE="$FILE(1)"
            elif [ -f $ZMQ_DIR/doc/$FILE.3 ]; then
                TITLE="$FILE(3)"
            else
                TITLE="$FILE(7)"
            fi
            python ./sendpage.py $CATEGORY $FILE $TITLE
        done
    fi

    echo "Cleaning up..."
    rm *.wd
}

if [ ! -z "$2" -a ! -z "$3" ]; then
    echo "Processing $2 branch in $1..."
    do_branch $2 $3
else
    echo "Processing all versions in $ZMQ_DIR..."
    #   Build and upload all versions
    #   Comment out whatever you don't need
    do_branch master  master
    do_branch v2.1.0  2-1-0
    do_branch v2.0.10 2-0-10
    do_branch v2.0.9  2-0-9
    do_branch v2.0.8  2-0-8
    do_branch v2.0.7  2-0-7
    do_branch v2.0.6  2-0-6
fi

#   Restore zeromq2 repository to master branch
cd $ZMQ_DIR
git checkout master
cd $OWN_DIR
