#! /bin/bash
#
#   apiall - Upload all ZeroMQ manuals to api.zero.mq
#   Part of the ztools/apisite toolkit.
#
#   Author: Pieter Hintjens <ph@imatix.com>
#   License: public domain
#
#   syntax: apiall
#
#   Requires these gits be checked out parallel to the ztools git:
#
#   zeromq3-x - 3.x release
#   zeromq4-x - 4.x release
#   zeromq4-1 - 4.1 release
#   libzmq    - 4.2 release
#
TOOLDIR=`dirname $0`

#               Directory        Tag      Category
$TOOLDIR/apione ../../zeromq3-x  master   ZMQ3-2
$TOOLDIR/apione ../../zeromq4-x  master   ZMQ4-0
$TOOLDIR/apione ../../zeromq4-1  master   ZMQ4-1
$TOOLDIR/apione ../../libzmq     v4.2.1   ZMQ4-2
$TOOLDIR/apione ../../libzmq     master   ZMQ-master
